using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using sp18Team7Final.Models;
using sp18Team7Final.Migrations;
using sp18Team7Final.DAL;
using System.Data.Entity.Migrations;

namespace sp18Team7Final.Migrations
{
    public class MovieData
    {
        public void SeedMovies(AppDbContext db)
        {
            Movie r1 = new Movie();
            r1.Title = "42nd Street";
            r1.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Musical"));
            r1.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Comedy"));
            r1.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Romance"));
            r1.Tagline = "OK. Say, Jones and Barry are doin' a show! - That's great. Jones and Barry are doin' a show.";
            r1.ReleaseDate = Convert.ToDateTime("2/2/1933");
            r1.MPAARating = MPAARating.Unrated;
            r1.Runtime = 89;
            r1.Actors = "Warner Baxter, Bebe Daniels, George Brent, Ruby Keeler, Guy Kibbee, Una Merkel";
            db.Movies.AddOrUpdate(r => r.Title, r1);
            db.SaveChanges();

            Movie r2 = new Movie();
            r2.Title = "It Happened One Night";
            r2.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Comedy"));
            r2.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Romance"));
            r2.Tagline = "TOGETHER... for the first time";
            r2.ReleaseDate = Convert.ToDateTime("2/22/1934");
            r2.MPAARating = MPAARating.Unrated;
            r2.Runtime = 105;
            r2.Actors = "Clark Gable, Claudette Colbert, Walter Connolly, Roscoe Karns, Jameson Thomas, Alan Hale";
            db.Movies.AddOrUpdate(r => r.Title, r2);
            db.SaveChanges();

            Movie r3 = new Movie();
            r3.Title = "Snow White and the Seven Dwarfs";
            r3.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Fantasy"));
            r3.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Animation"));
            r3.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Family"));
            r3.Tagline = "The Happiest, Dopiest, Grumpiest, Sneeziest movie of the year.";
            r3.ReleaseDate = Convert.ToDateTime("12/20/1937");
            r3.MPAARating = MPAARating.G;
            r3.Runtime = 83;
            r3.Actors = "Adriana Caselotti, Lucille La Verne, Harry Stockwell, Roy Atwell, Pinto Colvig, Otis Harlan";
            db.Movies.AddOrUpdate(r => r.Title, r3);
            db.SaveChanges();

            Movie r4 = new Movie();
            r4.Title = "The Wizard of Oz";
            r4.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Adventure"));
            r4.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Family"));
            r4.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Fantasy"));
            r4.Tagline = "We're off to see the Wizard, the wonderful Wizard of Oz!";
            r4.ReleaseDate = Convert.ToDateTime("8/15/1939");
            r4.MPAARating = MPAARating.PG;
            r4.Runtime = 102;
            r4.Actors = "Judy Garland, Frank Morgan, Ray Bolger, Bert Lahr, Jack Haley, Billie Burke";
            db.Movies.AddOrUpdate(r => r.Title, r4);
            db.SaveChanges();

            Movie r5 = new Movie();
            r5.Title = "Mr. Smith Goes to Washington";
            r5.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Drama"));
            r5.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Romance"));
            r5.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "War"));
            r5.Tagline = "Romance, drama, laughter and heartbreak... created out of the very heart and soil of America!";
            r5.ReleaseDate = Convert.ToDateTime("10/19/1939");
            r5.MPAARating = MPAARating.Unrated;
            r5.Runtime = 129;
            r5.Actors = "James Stewart, Jean Arthur, Claude Rains, Edward Arnold, Guy Kibbee, Thomas Mitchell";
            db.Movies.AddOrUpdate(r => r.Title, r5);
            db.SaveChanges();

            Movie r6 = new Movie();
            r6.Title = "Gone with the Wind";
            r6.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Drama"));
            r6.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Romance"));
            r6.Tagline = "The greatest romance of all time!";
            r6.ReleaseDate = Convert.ToDateTime("12/15/1939");
            r6.MPAARating = MPAARating.G;
            r6.Runtime = 238;
            r6.Actors = "Vivien Leigh, Clark Gable, Olivia de Havilland, Thomas Mitchell, Leslie Howard, Barbara O'Neil";
            db.Movies.AddOrUpdate(r => r.Title, r6);
            db.SaveChanges();

            Movie r7 = new Movie();
            r7.Title = "Casablanca";
            r7.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Drama"));
            r7.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Romance"));
            r7.Tagline = "They had a date with fate in Casablanca!";
            r7.ReleaseDate = Convert.ToDateTime("11/26/1942");
            r7.MPAARating = MPAARating.PG;
            r7.Runtime = 102;
            r7.Actors = "Humphrey Bogart, Ingrid Bergman, Paul Henreid, Claude Rains, Conrad Veidt, Sydney Greenstreet";
            db.Movies.AddOrUpdate(r => r.Title, r7);
            db.SaveChanges();

            Movie r8 = new Movie();
            r8.Title = "It's a Wonderful Life";
            r8.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Drama"));
            r8.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Family"));
            r8.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Fantasy"));
            r8.Tagline = "It's a wonderful laugh! It's a wonderful love!";
            r8.ReleaseDate = Convert.ToDateTime("12/20/1946");
            r8.MPAARating = MPAARating.PG;
            r8.Runtime = 130;
            r8.Actors = "James Stewart, Donna Reed, Lionel Barrymore, Thomas Mitchell, Henry Travers, Beulah Bondi";
            db.Movies.AddOrUpdate(r => r.Title, r8);
            db.SaveChanges();

            Movie r9 = new Movie();
            r9.Title = "Annie Get Your Gun";
            r9.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Comedy"));
            r9.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Musical"));
            r9.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Romance"));
            r9.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Western"));
            r9.Tagline = "Biggest musical under the sun!";
            r9.ReleaseDate = Convert.ToDateTime("5/17/1950");
            r9.MPAARating = MPAARating.Unrated;
            r9.Runtime = 107;
            r9.Actors = "Betty Hutton, Howard Keel, Louis Calhern, J. Carrol Naish, Edward Arnold, Keenan Wynn";
            db.Movies.AddOrUpdate(r => r.Title, r9);
            db.SaveChanges();

            Movie r10 = new Movie();
            r10.Title = "A Streetcar Named Desire";
            r10.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Drama"));
            r10.Tagline = "...Blanche, who wanted so much to stay a lady...";
            r10.ReleaseDate = Convert.ToDateTime("9/18/1951");
            r10.MPAARating = MPAARating.PG;
            r10.Runtime = 125;
            r10.Actors = "Vivien Leigh, Marlon Brando, Kim Hunter, Karl Malden, Rudy Bond, Nick Dennis";
            db.Movies.AddOrUpdate(r => r.Title, r10);
            db.SaveChanges();

            Movie r11 = new Movie();
            r11.Title = "Singin' in the Rain";
            r11.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Comedy"));
            r11.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Musical"));
            r11.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Romance"));
            r11.Tagline = "What a Glorious Feeling!";
            r11.ReleaseDate = Convert.ToDateTime("4/10/1952");
            r11.MPAARating = MPAARating.G;
            r11.Runtime = 103;
            r11.Actors = "Gene Kelly, Donald O'Connor, Debbie Reynolds, Jean Hagen, Millard Mitchell, Cyd Charisse";
            db.Movies.AddOrUpdate(r => r.Title, r11);
            db.SaveChanges();

            Movie r12 = new Movie();
            r12.Title = "Cat on a Hot Tin Roof";
            r12.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Drama"));
            r12.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Romance"));
            r12.Tagline = "Just one pillow on her bed ... and just one desire in her heart!";
            r12.ReleaseDate = Convert.ToDateTime("2/17/1958");
            r12.MPAARating = MPAARating.Unrated;
            r12.Runtime = 108;
            r12.Actors = "Elizabeth Taylor, Paul Newman, Burl Ives, Judith Anderson, Jack Carson, Madeleine Sherwood";
            db.Movies.AddOrUpdate(r => r.Title, r12);
            db.SaveChanges();

            Movie r13 = new Movie();
            r13.Title = "Some Like It Hot";
            r13.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Comedy"));
            r13.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Romance"));
            r13.Tagline = "The movie too HOT for words!";
            r13.ReleaseDate = Convert.ToDateTime("3/18/1959");
            r13.MPAARating = MPAARating.Unrated;
            r13.Runtime = 122;
            r13.Actors = "Marilyn Monroe, Tony Curtis, Jack Lemmon, George Raft, Pat O\u2019Brien, Joe E. Brown";
            db.Movies.AddOrUpdate(r => r.Title, r13);
            db.SaveChanges();

            Movie r14 = new Movie();
            r14.Title = "Psycho";
            r14.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Drama"));
            r14.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Horror"));
            r14.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Thriller"));
            r14.Tagline = "The master of suspense moves his cameras into the icy blackness of the unexplored!";
            r14.ReleaseDate = Convert.ToDateTime("6/16/1960");
            r14.MPAARating = MPAARating.R;
            r14.Runtime = 109;
            r14.Actors = "Anthony Perkins, Vera Miles, John Gavin, Janet Leigh, Martin Balsam, John McIntire";
            db.Movies.AddOrUpdate(r => r.Title, r14);
            db.SaveChanges();

            Movie r15 = new Movie();
            r15.Title = "West Side Story";
            r15.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Crime"));
            r15.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Drama"));
            r15.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Musical"));
            r15.Tagline = "The screen achieves one of the great entertainments in the history of motion pictures";
            r15.ReleaseDate = Convert.ToDateTime("10/18/1961");
            r15.MPAARating = MPAARating.Unrated;
            r15.Runtime = 152;
            r15.Actors = "Natalie Wood, Richard Beymer, Russ Tamblyn, Rita Moreno, George Chakiris, Simon Oakland";
            db.Movies.AddOrUpdate(r => r.Title, r15);
            db.SaveChanges();

            Movie r16 = new Movie();
            r16.Title = "The Man Who Shot Liberty Valance";
            r16.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Western"));
            r16.Tagline = "Together For The First Time - James Stewart - John Wayne - in the masterpiece of four-time Academy Award winner John Ford";
            r16.ReleaseDate = Convert.ToDateTime("4/22/1962");
            r16.MPAARating = MPAARating.Unrated;
            r16.Runtime = 123;
            r16.Actors = "John Wayne, James Stewart, Vera Miles, Lee Marvin, Edmond O'Brien, Ken Murray";
            db.Movies.AddOrUpdate(r => r.Title, r16);
            db.SaveChanges();

            Movie r17 = new Movie();
            r17.Title = "Dr. No";
            r17.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Adventure"));
            r17.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Action"));
            r17.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Thriller"));
            r17.Tagline = "NOW meet the most extraordinary gentleman spy in all fiction!";
            r17.ReleaseDate = Convert.ToDateTime("10/4/1962");
            r17.MPAARating = MPAARating.PG;
            r17.Runtime = 110;
            r17.Actors = "Sean Connery, Ursula Andress, Joseph Wiseman, Jack Lord, Bernard Lee, Anthony Dawson";
            db.Movies.AddOrUpdate(r => r.Title, r17);
            db.SaveChanges();

            Movie r18 = new Movie();
            r18.Title = "Lawrence of Arabia";
            r18.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Adventure"));
            r18.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Drama"));
            r18.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "History"));
            r18.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "War"));
            r18.Tagline = "A Mighty Motion Picture Of Action And Adventure!";
            r18.ReleaseDate = Convert.ToDateTime("12/10/1962");
            r18.MPAARating = MPAARating.PG;
            r18.Runtime = 216;
            r18.Actors = "Peter O'Toole, Alec Guinness, Anthony Quinn, Jack Hawkins, Omar Sharif, Claude Rains";
            db.Movies.AddOrUpdate(r => r.Title, r18);
            db.SaveChanges();

            Movie r19 = new Movie();
            r19.Title = "To Kill a Mockingbird";
            r19.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Crime"));
            r19.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Drama"));
            r19.Tagline = "The most beloved Pulitzer Prize book now comes vividly alive on the screen! ";
            r19.ReleaseDate = Convert.ToDateTime("12/25/1962");
            r19.MPAARating = MPAARating.Unrated;
            r19.Runtime = 129;
            r19.Actors = "Gregory Peck, Brock Peters, James Anderson, Mary Badham, Phillip Alford, John Megna";
            db.Movies.AddOrUpdate(r => r.Title, r19);
            db.SaveChanges();

            Movie r20 = new Movie();
            r20.Title = "A Hard Day's Night";
            r20.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Comedy"));
            r20.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Musical"));
            r20.Tagline = "The Beatles, starring in their first full-length, hilarious, action-packed film!";
            r20.ReleaseDate = Convert.ToDateTime("7/6/1964");
            r20.MPAARating = MPAARating.G;
            r20.Runtime = 88;
            r20.Actors = "John Lennon, Paul McCartney, George Harrison, Ringo Starr, Wilfrid Brambell, Norman Rossington";
            db.Movies.AddOrUpdate(r => r.Title, r20);
            db.SaveChanges();

            Movie r21 = new Movie();
            r21.Title = "Mary Poppins";
            r21.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Comedy"));
            r21.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Fantasy"));
            r21.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Family"));
            r21.Tagline = "It's supercalifragilisticexpialidocious!";
            r21.ReleaseDate = Convert.ToDateTime("8/27/1964");
            r21.MPAARating = MPAARating.G;
            r21.Runtime = 139;
            r21.Actors = "Julie Andrews, Dick Van Dyke, David Tomlinson, Glynis Johns, Hermione Baddeley, Reta Shaw";
            db.Movies.AddOrUpdate(r => r.Title, r21);
            db.SaveChanges();

            Movie r22 = new Movie();
            r22.Title = "My Fair Lady";
            r22.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Drama"));
            r22.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Family"));
            r22.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Musical"));
            r22.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Romance"));
            r22.Tagline = "The loverliest motion picture of them all!";
            r22.ReleaseDate = Convert.ToDateTime("10/21/1964");
            r22.MPAARating = MPAARating.G;
            r22.Runtime = 170;
            r22.Actors = "Audrey Hepburn, Rex Harrison, Stanley Holloway, Wilfrid Hyde-White, Gladys Cooper, Jeremy Brett";
            db.Movies.AddOrUpdate(r => r.Title, r22);
            db.SaveChanges();

            Movie r23 = new Movie();
            r23.Title = "The Sound of Music";
            r23.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Drama"));
            r23.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Family"));
            r23.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Musical"));
            r23.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Romance"));
            r23.Tagline = "The happiest sound in all the world!";
            r23.ReleaseDate = Convert.ToDateTime("3/2/1965");
            r23.MPAARating = MPAARating.G;
            r23.Runtime = 174;
            r23.Actors = "Julie Andrews, Christopher Plummer, Eleanor Parker, Richard Haydn, Peggy Wood, Charmian Carr";
            db.Movies.AddOrUpdate(r => r.Title, r23);
            db.SaveChanges();

            Movie r24 = new Movie();
            r24.Title = "Butch Cassidy and the Sundance Kid";
            r24.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "History"));
            r24.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Drama"));
            r24.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Western"));
            r24.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Crime"));
            r24.Tagline = "Not that it matters, but most of it is true.";
            r24.ReleaseDate = Convert.ToDateTime("9/23/1969");
            r24.MPAARating = MPAARating.PG;
            r24.Runtime = 110;
            r24.Actors = "Paul Newman, Robert Redford, Katharine Ross, Strother Martin, Henry Jones, Jeff Corey";
            db.Movies.AddOrUpdate(r => r.Title, r24);
            db.SaveChanges();

            Movie r25 = new Movie();
            r25.Title = "Catch-22";
            r25.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "War"));
            r25.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Drama"));
            r25.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Comedy"));
            r25.Tagline = "The anti-war satire of epic proportions.";
            r25.ReleaseDate = Convert.ToDateTime("6/24/1970");
            r25.MPAARating = MPAARating.R;
            r25.Runtime = 121;
            r25.Actors = "Martin Balsam, Richard Benjamin, Art Garfunkel, Jack Gilford, Buck Henry, Bob Newhart";
            db.Movies.AddOrUpdate(r => r.Title, r25);
            db.SaveChanges();

            Movie r26 = new Movie();
            r26.Title = "Willy Wonka & the Chocolate Factory";
            r26.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Family"));
            r26.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Fantasy"));
            r26.Tagline = "It's Scrumdiddlyumptious!";
            r26.ReleaseDate = Convert.ToDateTime("6/29/1971");
            r26.MPAARating = MPAARating.G;
            r26.Runtime = 100;
            r26.Actors = "Gene Wilder, Jack Albertson, Peter Ostrum, Roy Kinnear, Denise Nickerson, Leonard Stone";
            db.Movies.AddOrUpdate(r => r.Title, r26);
            db.SaveChanges();

            Movie r27 = new Movie();
            r27.Title = "Fiddler on the Roof";
            r27.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Drama"));
            r27.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Romance"));
            r27.Tagline = "To Life!";
            r27.ReleaseDate = Convert.ToDateTime("11/3/1971");
            r27.MPAARating = MPAARating.G;
            r27.Runtime = 181;
            r27.Actors = "Chaim Topol, Norma Crane, Leonard Frey, Molly Picon, Paul Mann, Rosalind Harris";
            db.Movies.AddOrUpdate(r => r.Title, r27);
            db.SaveChanges();

            Movie r28 = new Movie();
            r28.Title = "Diamonds Are Forever";
            r28.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Adventure"));
            r28.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == " Action"));
            r28.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Thriller"));
            r28.Tagline = "The man who made 007 a household number";
            r28.ReleaseDate = Convert.ToDateTime("12/13/1971");
            r28.MPAARating = MPAARating.PG;
            r28.Runtime = 120;
            r28.Actors = "Sean Connery, Jill St. John, Charles Gray, Lana Wood, Jimmy Dean, Bruce Cabot";
            db.Movies.AddOrUpdate(r => r.Title, r28);
            db.SaveChanges();

            Movie r29 = new Movie();
            r29.Title = "American Graffiti";
            r29.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Comedy"));
            r29.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Drama"));
            r29.Tagline = "Where were you in '62?";
            r29.ReleaseDate = Convert.ToDateTime("8/1/1973");
            r29.MPAARating = MPAARating.PG;
            r29.Runtime = 110;
            r29.Actors = "Richard Dreyfuss, Ron Howard, Paul Le Mat, Charles Martin Smith, Cindy Williams, Candy Clark";
            db.Movies.AddOrUpdate(r => r.Title, r29);
            db.SaveChanges();

            Movie r30 = new Movie();
            r30.Title = "The Sting";
            r30.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Comedy"));
            r30.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Crime"));
            r30.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == " Drama"));
            r30.Tagline = "...all it takes is a little confidence.";
            r30.ReleaseDate = Convert.ToDateTime("12/25/1973");
            r30.MPAARating = MPAARating.PG;
            r30.Runtime = 129;
            r30.Actors = "Paul Newman, Robert Redford, Robert Shaw, Charles Durning, Ray Walston, Eileen Brennan";
            db.Movies.AddOrUpdate(r => r.Title, r30);
            db.SaveChanges();

            Movie r31 = new Movie();
            r31.Title = "The Exorcist";
            r31.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Drama"));
            r31.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Horror"));
            r31.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Thriller"));
            r31.Tagline = "Something almost beyond comprehension is happening to a girl on this street, in this house... and a man has been sent for as a last resort. This man is The Exorcist.";
            r31.ReleaseDate = Convert.ToDateTime("12/26/1973");
            r31.MPAARating = MPAARating.R;
            r31.Runtime = 122;
            r31.Actors = "Linda Blair, Max von Sydow, Ellen Burstyn, Jason Miller, Lee J. Cobb, Kitty Winn";
            db.Movies.AddOrUpdate(r => r.Title, r31);
            db.SaveChanges();

            Movie r32 = new Movie();
            r32.Title = "Blazing Saddles";
            r32.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Western"));
            r32.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Comedy"));
            r32.Tagline = "Never give a saga an even break!";
            r32.ReleaseDate = Convert.ToDateTime("2/7/1974");
            r32.MPAARating = MPAARating.R;
            r32.Runtime = 93;
            r32.Actors = "Cleavon Little, Gene Wilder, Harvey Korman, Slim Pickens, Madeline Kahn, Mel Brooks";
            db.Movies.AddOrUpdate(r => r.Title, r32);
            db.SaveChanges();

            Movie r33 = new Movie();
            r33.Title = "Monty Python and the Holy Grail";
            r33.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Adventure"));
            r33.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Fantasy"));
            r33.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Comedy"));
            r33.Tagline = "And now! At Last! Another film completely different from some of the other films which aren't quite the same as this one is.";
            r33.ReleaseDate = Convert.ToDateTime("3/13/1975");
            r33.MPAARating = MPAARating.PG;
            r33.Runtime = 91;
            r33.Actors = "Graham Chapman, John Cleese, Terry Gilliam, Eric Idle, Terry Jones, Michael Palin";
            db.Movies.AddOrUpdate(r => r.Title, r33);
            db.SaveChanges();

            Movie r34 = new Movie();
            r34.Title = "Jaws";
            r34.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Horror"));
            r34.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Adventure"));
            r34.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Thriller"));
            r34.Tagline = "Don't go in the water.";
            r34.ReleaseDate = Convert.ToDateTime("6/18/1975");
            r34.MPAARating = MPAARating.PG;
            r34.Runtime = 124;
            r34.Actors = "Roy Scheider, Robert Shaw, Richard Dreyfuss, Lorraine Gary, Murray Hamilton, Carl Gottlieb";
            db.Movies.AddOrUpdate(r => r.Title, r34);
            db.SaveChanges();

            Movie r35 = new Movie();
            r35.Title = "Star Wars";
            r35.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Adventure"));
            r35.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Science Fiction"));
            r35.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Action"));
            r35.Tagline = "A long time ago in a galaxy far, far away...";
            r35.ReleaseDate = Convert.ToDateTime("5/25/1977");
            r35.MPAARating = MPAARating.PG;
            r35.Runtime = 121;
            r35.Actors = "Mark Hamill, Harrison Ford, Carrie Fisher, Peter Cushing, Alec Guinness, Anthony Daniels";
            db.Movies.AddOrUpdate(r => r.Title, r35);
            db.SaveChanges();

            Movie r36 = new Movie();
            r36.Title = "The Spy Who Loved Me";
            r36.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Adventure"));
            r36.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Action"));
            r36.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Thriller"));
            r36.Tagline = "It's the BIGGEST. It's the BEST. It's BOND. And B-E-Y-O-N-D.";
            r36.ReleaseDate = Convert.ToDateTime("7/7/1977");
            r36.MPAARating = MPAARating.PG;
            r36.Runtime = 125;
            r36.Actors = "Roger Moore, Barbara Bach, Curd Joergens, Richard Kiel, Caroline Munro, Walter Gotell";
            db.Movies.AddOrUpdate(r => r.Title, r36);
            db.SaveChanges();

            Movie r37 = new Movie();
            r37.Title = "Close Encounters of the Third Kind";
            r37.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Science Fiction"));
            r37.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Drama"));
            r37.Tagline = "We are not alone.";
            r37.ReleaseDate = Convert.ToDateTime("11/16/1977");
            r37.MPAARating = MPAARating.PG;
            r37.Runtime = 135;
            r37.Actors = "Richard Dreyfuss, Francois Truffaut, Teri Garr, Melinda Dillon, Bob Balaban, J. Patrick McNamara";
            db.Movies.AddOrUpdate(r => r.Title, r37);
            db.SaveChanges();

            Movie r38 = new Movie();
            r38.Title = "Grease";
            r38.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Romance"));
            r38.Tagline = "Grease is the word";
            r38.ReleaseDate = Convert.ToDateTime("7/7/1978");
            r38.MPAARating = MPAARating.PG13;
            r38.Runtime = 110;
            r38.Actors = "John Travolta, Olivia Newton-John, Stockard Channing, Jeff Conaway, Didi Conn, Barry Pearl";
            db.Movies.AddOrUpdate(r => r.Title, r38);
            db.SaveChanges();

            Movie r39 = new Movie();
            r39.Title = "Animal House";
            r39.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Comedy"));
            r39.Tagline = "It was the Deltas against the rules... the rules lost!";
            r39.ReleaseDate = Convert.ToDateTime("7/27/1978");
            r39.MPAARating = MPAARating.R;
            r39.Runtime = 109;
            r39.Actors = "John Belushi, Tim Matheson, John Vernon, Verna Bloom, Tom Hulce, Cesare Danova";
            db.Movies.AddOrUpdate(r => r.Title, r39);
            db.SaveChanges();

            Movie r40 = new Movie();
            r40.Title = "Halloween";
            r40.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Horror"));
            r40.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Thriller"));
            r40.Tagline = "The Night He Came Home";
            r40.ReleaseDate = Convert.ToDateTime("10/25/1978");
            r40.MPAARating = MPAARating.R;
            r40.Runtime = 91;
            r40.Actors = "Donald Pleasence, Jamie Lee Curtis, P.J. Soles, Nancy Kyes, Nick Castle, Tony Moran";
            db.Movies.AddOrUpdate(r => r.Title, r40);
            db.SaveChanges();

            Movie r41 = new Movie();
            r41.Title = "Alien";
            r41.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Horror"));
            r41.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Action"));
            r41.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Thriller"));
            r41.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Science Fiction"));
            r41.Tagline = "In space no one can hear you scream.";
            r41.ReleaseDate = Convert.ToDateTime("5/25/1979");
            r41.MPAARating = MPAARating.R;
            r41.Runtime = 117;
            r41.Actors = "Tom Skerritt, Sigourney Weaver, Veronica Cartwright, Harry Dean Stanton, John Hurt, Ian Holm";
            db.Movies.AddOrUpdate(r => r.Title, r41);
            db.SaveChanges();

            Movie r42 = new Movie();
            r42.Title = "The Muppet Movie";
            r42.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Adventure"));
            r42.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Comedy"));
            r42.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Family"));
            r42.Tagline = "More entertaining than humanly possible.";
            r42.ReleaseDate = Convert.ToDateTime("5/31/1979");
            r42.MPAARating = MPAARating.G;
            r42.Runtime = 97;
            r42.Actors = "Jim Henson, Frank Oz, Jerry Nelson, Richard Hunt, Dave Goelz, Charles Durning";
            db.Movies.AddOrUpdate(r => r.Title, r42);
            db.SaveChanges();

            Movie r43 = new Movie();
            r43.Title = "Apocalypse Now";
            r43.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Drama"));
            r43.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "War"));
            r43.Tagline = "This is the end...";
            r43.ReleaseDate = Convert.ToDateTime("8/15/1979");
            r43.MPAARating = MPAARating.R;
            r43.Runtime = 153;
            r43.Actors = "Martin Sheen, Marlon Brando, Robert Duvall, Frederic Forrest, Sam Bottoms, Laurence Fishburne";
            db.Movies.AddOrUpdate(r => r.Title, r43);
            db.SaveChanges();

            Movie r44 = new Movie();
            r44.Title = "The Empire Strikes Back";
            r44.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Adventure"));
            r44.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Action"));
            r44.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Science Fiction"));
            r44.Tagline = "The Adventure Continues...";
            r44.ReleaseDate = Convert.ToDateTime("5/17/1980");
            r44.MPAARating = MPAARating.PG;
            r44.Runtime = 124;
            r44.Actors = "Mark Hamill, Harrison Ford, Carrie Fisher, Billy Dee Williams, Anthony Daniels, David Prowse";
            db.Movies.AddOrUpdate(r => r.Title, r44);
            db.SaveChanges();

            Movie r45 = new Movie();
            r45.Title = "The Shining";
            r45.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Horror"));
            r45.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Thriller"));
            r45.Tagline = "A masterpiece of modern horror.";
            r45.ReleaseDate = Convert.ToDateTime("5/22/1980");
            r45.MPAARating = MPAARating.R;
            r45.Runtime = 144;
            r45.Actors = "Jack Nicholson, Shelley Duvall, Danny Lloyd, Scatman Crothers, Barry Nelson, Philip Stone";
            db.Movies.AddOrUpdate(r => r.Title, r45);
            db.SaveChanges();

            Movie r46 = new Movie();
            r46.Title = "Airplane!";
            r46.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Comedy"));
            r46.Tagline = "What's slower than a speeding bullet, and able to hit tall buildings at a single bound?";
            r46.ReleaseDate = Convert.ToDateTime("7/2/1980");
            r46.MPAARating = MPAARating.PG;
            r46.Runtime = 88;
            r46.Actors = "Robert Hays, Julie Hagerty, Kareem Abdul-Jabbar, Lloyd Bridges, Peter Graves, Leslie Nielsen";
            db.Movies.AddOrUpdate(r => r.Title, r46);
            db.SaveChanges();

            Movie r47 = new Movie();
            r47.Title = "Caddyshack";
            r47.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Comedy"));
            r47.Tagline = "The snobs against the slobs!";
            r47.ReleaseDate = Convert.ToDateTime("7/25/1980");
            r47.MPAARating = MPAARating.R;
            r47.Runtime = 98;
            r47.Actors = "Chevy Chase, Rodney Dangerfield, Ted Knight, Michael O'Keefe, Bill Murray, Sarah Holcomb";
            db.Movies.AddOrUpdate(r => r.Title, r47);
            db.SaveChanges();

            Movie r48 = new Movie();
            r48.Title = "Raging Bull";
            r48.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Drama"));
            r48.Tagline = "";
            r48.ReleaseDate = Convert.ToDateTime("11/14/1980");
            r48.MPAARating = MPAARating.R;
            r48.Runtime = 129;
            r48.Actors = "Robert De Niro, Joe Pesci, Cathy Moriarty, Frank Vincent, Nicholas Colasanto, Theresa Saldana";
            db.Movies.AddOrUpdate(r => r.Title, r48);
            db.SaveChanges();

            Movie r49 = new Movie();
            r49.Title = "Raiders of the Lost Ark";
            r49.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Adventure"));
            r49.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Action"));
            r49.Tagline = "Indiana Jones - the new hero from the creators of JAWS and STAR WARS.";
            r49.ReleaseDate = Convert.ToDateTime("6/12/1981");
            r49.MPAARating = MPAARating.PG;
            r49.Runtime = 115;
            r49.Actors = "Harrison Ford, Karen Allen, Paul Freeman, Ronald Lacey, John Rhys-Davies, Denholm Elliott";
            db.Movies.AddOrUpdate(r => r.Title, r49);
            db.SaveChanges();

            Movie r50 = new Movie();
            r50.Title = "E.T. the Extra-Terrestrial";
            r50.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Science Fiction"));
            r50.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Adventure"));
            r50.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Family"));
            r50.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Fantasy"));
            r50.Tagline = "He is afraid. He is alone. He is three million light years from home.";
            r50.ReleaseDate = Convert.ToDateTime("4/3/1982");
            r50.MPAARating = MPAARating.PG;
            r50.Runtime = 115;
            r50.Actors = "Henry Thomas, Drew Barrymore, Robert MacNaughton, Dee Wallace, Peter Coyote, Erika Eleniak";
            db.Movies.AddOrUpdate(r => r.Title, r50);
            db.SaveChanges();

            Movie r51 = new Movie();
            r51.Title = "Fast Times at Ridgemont High";
            r51.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Comedy"));
            r51.Tagline = "Fast Cars, Fast Girls, Fast Carrots...Fast Carrots?";
            r51.ReleaseDate = Convert.ToDateTime("8/13/1982");
            r51.MPAARating = MPAARating.R;
            r51.Runtime = 90;
            r51.Actors = "Sean Penn, Jennifer Jason Leigh, Judge Reinhold, Phoebe Cates, Brian Backer, Robert Romanus";
            db.Movies.AddOrUpdate(r => r.Title, r51);
            db.SaveChanges();

            Movie r52 = new Movie();
            r52.Title = "Return of the Jedi";
            r52.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Adventure"));
            r52.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Action"));
            r52.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Science Fiction"));
            r52.Tagline = "The Empire Falls...";
            r52.ReleaseDate = Convert.ToDateTime("5/23/1983");
            r52.MPAARating = MPAARating.PG;
            r52.Runtime = 135;
            r52.Actors = "Mark Hamill, Harrison Ford, Carrie Fisher, Billy Dee Williams, Anthony Daniels, David Prowse";
            db.Movies.AddOrUpdate(r => r.Title, r52);
            db.SaveChanges();

            Movie r53 = new Movie();
            r53.Title = "WarGames";
            r53.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Thriller"));
            r53.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Science Fiction"));
            r53.Tagline = "Is it a game, or is it real?";
            r53.ReleaseDate = Convert.ToDateTime("6/3/1983");
            r53.MPAARating = MPAARating.PG;
            r53.Runtime = 114;
            r53.Actors = "Matthew Broderick, Dabney Coleman, Ally Sheedy, John Wood, Barry Corbin, Juanin Clay";
            db.Movies.AddOrUpdate(r => r.Title, r53);
            db.SaveChanges();

            Movie r54 = new Movie();
            r54.Title = "Trading Places";
            r54.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Comedy"));
            r54.Tagline = "Some very funny business.";
            r54.ReleaseDate = Convert.ToDateTime("6/7/1983");
            r54.MPAARating = MPAARating.R;
            r54.Runtime = 116;
            r54.Actors = "Eddie Murphy, Dan Aykroyd, Jamie Lee Curtis, Jim Belushi, Denholm Elliott, Ralph Bellamy";
            db.Movies.AddOrUpdate(r => r.Title, r54);
            db.SaveChanges();

            Movie r55 = new Movie();
            r55.Title = "A Christmas Story";
            r55.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Comedy"));
            r55.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Family"));
            r55.Tagline = "Peace, Harmony, Comfort and Joy... Maybe Next Year.";
            r55.ReleaseDate = Convert.ToDateTime("11/18/1983");
            r55.MPAARating = MPAARating.PG;
            r55.Runtime = 94;
            r55.Actors = "Melinda Dillon, Darren McGavin, Peter Billingsley, Jean Shepherd, Ian Petrella, Scott Schwartz";
            db.Movies.AddOrUpdate(r => r.Title, r55);
            db.SaveChanges();

            Movie r56 = new Movie();
            r56.Title = "Footloose";
            r56.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Drama"));
            r56.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Family"));
            r56.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Musical"));
            r56.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Romance"));
            r56.Tagline = "He's a big-city kid in a small town. They said he'd never win. He knew he had to.";
            r56.ReleaseDate = Convert.ToDateTime("2/17/1984");
            r56.MPAARating = MPAARating.PG;
            r56.Runtime = 107;
            r56.Actors = "Kevin Bacon, John Lithgow, Dianne Wiest, Chris Penn, Lori Singer, Sarah Jessica Parker";
            db.Movies.AddOrUpdate(r => r.Title, r56);
            db.SaveChanges();

            Movie r57 = new Movie();
            r57.Title = "Back to the Future";
            r57.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Adventure"));
            r57.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Comedy"));
            r57.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Science Fiction"));
            r57.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Family"));
            r57.Tagline = "He's the only kid ever to get into trouble before he was born.";
            r57.ReleaseDate = Convert.ToDateTime("7/3/1985");
            r57.MPAARating = MPAARating.PG;
            r57.Runtime = 116;
            r57.Actors = "Michael J. Fox, Christopher Lloyd, Lea Thompson, Crispin Glover, Thomas F. Wilson, Claudia Wells";
            db.Movies.AddOrUpdate(r => r.Title, r57);
            db.SaveChanges();

            Movie r58 = new Movie();
            r58.Title = "The Color Purple";
            r58.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Drama"));
            r58.Tagline = "It's about life. It's about love. It's about us.";
            r58.ReleaseDate = Convert.ToDateTime("12/18/1985");
            r58.MPAARating = MPAARating.PG13;
            r58.Runtime = 154;
            r58.Actors = "Whoopi Goldberg, Margaret Avery, Danny Glover, Akosua Busia, Oprah Winfrey, Willard E. Pugh";
            db.Movies.AddOrUpdate(r => r.Title, r58);
            db.SaveChanges();

            Movie r59 = new Movie();
            r59.Title = "Top Gun";
            r59.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Action"));
            r59.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Romance"));
            r59.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "War"));
            r59.Tagline = "Up there with the best of the best.";
            r59.ReleaseDate = Convert.ToDateTime("5/16/1986");
            r59.MPAARating = MPAARating.PG;
            r59.Runtime = 110;
            r59.Actors = "Tom Cruise, Kelly McGillis, Val Kilmer, Anthony Edwards, Tom Skerritt, Michael Ironside";
            db.Movies.AddOrUpdate(r => r.Title, r59);
            db.SaveChanges();

            Movie r60 = new Movie();
            r60.Title = "Little Shop of Horrors";
            r60.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Horror"));
            r60.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Musical"));
            r60.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Comedy"));
            r60.Tagline = "Don't feed the plants.";
            r60.ReleaseDate = Convert.ToDateTime("12/19/1986");
            r60.MPAARating = MPAARating.PG13;
            r60.Runtime = 94;
            r60.Actors = "Rick Moranis, Ellen Greene, Vincent Gardenia, Steve Martin, Tisha Campbell-Martin, John Candy";
            db.Movies.AddOrUpdate(r => r.Title, r60);
            db.SaveChanges();

            Movie r61 = new Movie();
            r61.Title = "Spaceballs";
            r61.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Comedy"));
            r61.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Science Fiction"));
            r61.Tagline = "May the schwartz be with you";
            r61.ReleaseDate = Convert.ToDateTime("6/24/1987");
            r61.MPAARating = MPAARating.PG;
            r61.Runtime = 96;
            r61.Actors = "Mel Brooks, Rick Moranis, Bill Pullman, Daphne Zuniga, John Candy, George Wyner";
            db.Movies.AddOrUpdate(r => r.Title, r61);
            db.SaveChanges();

            Movie r62 = new Movie();
            r62.Title = "The Princess Bride";
            r62.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Adventure"));
            r62.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Family"));
            r62.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Fantasy"));
            r62.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Comedy"));
            r62.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Romance"));
            r62.Tagline = "It's as real as the feelings you feel.";
            r62.ReleaseDate = Convert.ToDateTime("9/18/1987");
            r62.MPAARating = MPAARating.PG;
            r62.Runtime = 98;
            r62.Actors = "Cary Elwes, Robin Wright, Mandy Patinkin, Andre the Giant, Chris Sarandon, Christopher Guest";
            db.Movies.AddOrUpdate(r => r.Title, r62);
            db.SaveChanges();

            Movie r63 = new Movie();
            r63.Title = "Big";
            r63.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Fantasy"));
            r63.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Drama"));
            r63.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Comedy"));
            r63.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Romance"));
            r63.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Family"));
            r63.Tagline = "You're Only Young Once But For Josh It Might Just Last A Lifetime.";
            r63.ReleaseDate = Convert.ToDateTime("6/3/1988");
            r63.MPAARating = MPAARating.PG;
            r63.Runtime = 104;
            r63.Actors = "Tom Hanks, Elizabeth Perkins, Robert Loggia, John Heard, Jared Rushton, David Moscow";
            db.Movies.AddOrUpdate(r => r.Title, r63);
            db.SaveChanges();

            Movie r64 = new Movie();
            r64.Title = "The Land Before Time";
            r64.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Animation"));
            r64.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Adventure"));
            r64.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Family"));
            r64.Tagline = "A new adventure is born.";
            r64.ReleaseDate = Convert.ToDateTime("11/18/1988");
            r64.MPAARating = MPAARating.G;
            r64.Runtime = 69;
            r64.Actors = "Gabriel Damon, Candace Hutson, Judith Barsi, Will Ryan, Pat Hingle, Helen Shaver";
            db.Movies.AddOrUpdate(r => r.Title, r64);
            db.SaveChanges();

            Movie r65 = new Movie();
            r65.Title = "Rain Man";
            r65.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Drama"));
            r65.Tagline = "A journey through understanding and fellowship.";
            r65.ReleaseDate = Convert.ToDateTime("12/11/1988");
            r65.MPAARating = MPAARating.R;
            r65.Runtime = 133;
            r65.Actors = "Dustin Hoffman, Tom Cruise, Valeria Golino, Gerald R. Molen, Jack Murdock, Michael D. Roberts";
            db.Movies.AddOrUpdate(r => r.Title, r65);
            db.SaveChanges();

            Movie r66 = new Movie();
            r66.Title = "Bill & Ted's Excellent Adventure";
            r66.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Adventure"));
            r66.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Comedy"));
            r66.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Science Fiction"));
            r66.Tagline = "History is about to be rewritten by two guys who can't spell.";
            r66.ReleaseDate = Convert.ToDateTime("2/17/1989");
            r66.MPAARating = MPAARating.PG;
            r66.Runtime = 90;
            r66.Actors = "Keanu Reeves, Alex Winter, George Carlin, Dan Shor, Hal Landon Jr., Amy Stock-Poynton";
            db.Movies.AddOrUpdate(r => r.Title, r66);
            db.SaveChanges();

            Movie r67 = new Movie();
            r67.Title = "Dead Poets Society";
            r67.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Drama"));
            r67.Tagline = "He was their inspiration. He made their lives extraordinary.";
            r67.ReleaseDate = Convert.ToDateTime("6/2/1989");
            r67.MPAARating = MPAARating.PG;
            r67.Runtime = 129;
            r67.Actors = "Robin Williams, Ethan Hawke, Robert Sean Leonard, Gale Hansen, Josh Charles, Dylan Kussman";
            db.Movies.AddOrUpdate(r => r.Title, r67);
            db.SaveChanges();

            Movie r68 = new Movie();
            r68.Title = "When Harry Met Sally...";
            r68.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Comedy"));
            r68.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Romance"));
            r68.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Drama"));
            r68.Tagline = "Can two friends sleep together and still love each other in the morning?";
            r68.ReleaseDate = Convert.ToDateTime("7/21/1989");
            r68.MPAARating = MPAARating.R;
            r68.Runtime = 96;
            r68.Actors = "Meg Ryan, Billy Crystal, Carrie Fisher, Bruno Kirby, Steven Ford, Lisa Jane Persky";
            db.Movies.AddOrUpdate(r => r.Title, r68);
            db.SaveChanges();

            Movie r69 = new Movie();
            r69.Title = "Back to the Future Part II";
            r69.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Adventure"));
            r69.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Comedy"));
            r69.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Family"));
            r69.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Science Fiction"));
            r69.Tagline = "Roads? Where we're going, we don't need roads!";
            r69.ReleaseDate = Convert.ToDateTime("11/20/1989");
            r69.MPAARating = MPAARating.PG;
            r69.Runtime = 108;
            r69.Actors = "Michael J. Fox, Christopher Lloyd, Lea Thompson, Elisabeth Shue, James Tolkan, Jeffrey Weissman";
            db.Movies.AddOrUpdate(r => r.Title, r69);
            db.SaveChanges();

            Movie r70 = new Movie();
            r70.Title = "Back to the Future Part III";
            r70.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Adventure"));
            r70.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Comedy"));
            r70.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Family"));
            r70.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Science Fiction"));
            r70.Tagline = "They've saved the best trip for last... But this time they may have gone too far.";
            r70.ReleaseDate = Convert.ToDateTime("5/25/1990");
            r70.MPAARating = MPAARating.PG;
            r70.Runtime = 118;
            r70.Actors = "Michael J. Fox, Christopher Lloyd, Mary Steenburgen, Thomas F. Wilson, Lea Thompson, Elisabeth Shue";
            db.Movies.AddOrUpdate(r => r.Title, r70);
            db.SaveChanges();

            Movie r71 = new Movie();
            r71.Title = "Robin Hood: Prince of Thieves";
            r71.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Adventure"));
            r71.Tagline = "For the good of all men, and the love of one woman, he fought to uphold justice by breaking the law.";
            r71.ReleaseDate = Convert.ToDateTime("6/14/1991");
            r71.MPAARating = MPAARating.PG13;
            r71.Runtime = 143;
            r71.Actors = "Kevin Costner, Morgan Freeman, Christian Slater, Mary Elizabeth Mastrantonio, Alan Rickman, Geraldine McEwan";
            db.Movies.AddOrUpdate(r => r.Title, r71);
            db.SaveChanges();

            Movie r72 = new Movie();
            r72.Title = "Wayne's World";
            r72.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Comedy"));
            r72.Tagline = "You'll laugh. You'll cry. You'll hurl.";
            r72.ReleaseDate = Convert.ToDateTime("2/14/1992");
            r72.MPAARating = MPAARating.PG13;
            r72.Runtime = 94;
            r72.Actors = "Mike Myers, Dana Carvey, Rob Lowe, Tia Carrere, Lara Flynn Boyle, Chris Farley";
            db.Movies.AddOrUpdate(r => r.Title, r72);
            db.SaveChanges();

            Movie r73 = new Movie();
            r73.Title = "A League of Their Own";
            r73.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Comedy"));
            r73.Tagline = "To achieve the incredible, you have to attempt the impossible.";
            r73.ReleaseDate = Convert.ToDateTime("7/1/1992");
            r73.MPAARating = MPAARating.PG;
            r73.Runtime = 128;
            r73.Actors = "Tom Hanks, Geena Davis, Madonna, Lori Petty, Jon Lovitz, David Strathairn";
            db.Movies.AddOrUpdate(r => r.Title, r73);
            db.SaveChanges();

            Movie r74 = new Movie();
            r74.Title = "The Last of the Mohicans";
            r74.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Action"));
            r74.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Adventure"));
            r74.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Drama"));
            r74.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "History"));
            r74.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Romance"));
            r74.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "War"));
            r74.Tagline = "The first American hero.";
            r74.ReleaseDate = Convert.ToDateTime("9/25/1992");
            r74.MPAARating = MPAARating.R;
            r74.Runtime = 112;
            r74.Actors = "Daniel Day-Lewis, Madeleine Stowe, Russell Means, Eric Schweig, Jodhi May, Steven Waddington";
            db.Movies.AddOrUpdate(r => r.Title, r74);
            db.SaveChanges();

            Movie r75 = new Movie();
            r75.Title = "Aladdin";
            r75.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Animation"));
            r75.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Family"));
            r75.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Comedy"));
            r75.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Adventure"));
            r75.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Fantasy"));
            r75.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Romance"));
            r75.Tagline = "Wish granted!";
            r75.ReleaseDate = Convert.ToDateTime("11/25/1992");
            r75.MPAARating = MPAARating.G;
            r75.Runtime = 90;
            r75.Actors = "Scott Weinger, Robin Williams, Linda Larkin, Jonathan Freeman, Frank Welker, Gilbert Gottfried";
            db.Movies.AddOrUpdate(r => r.Title, r75);
            db.SaveChanges();

            Movie r76 = new Movie();
            r76.Title = "The Muppet Christmas Carol";
            r76.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Comedy"));
            r76.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Family"));
            r76.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Fantasy"));
            r76.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Drama"));
            r76.Tagline = "";
            r76.ReleaseDate = Convert.ToDateTime("12/10/1992");
            r76.MPAARating = MPAARating.G;
            r76.Runtime = 85;
            r76.Actors = "Michael Caine, Don Austen, Meredith Braun, Don Austen, Ed Sanders, Dave Goelz";
            db.Movies.AddOrUpdate(r => r.Title, r76);
            db.SaveChanges();

            Movie r77 = new Movie();
            r77.Title = "A Few Good Men";
            r77.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Drama"));
            r77.Tagline = "You can't handle the truth!";
            r77.ReleaseDate = Convert.ToDateTime("12/11/1992");
            r77.MPAARating = MPAARating.R;
            r77.Runtime = 138;
            r77.Actors = "Tom Cruise, Jack Nicholson, Demi Moore, Kevin Bacon, Kevin Pollak, James Marshall";
            db.Movies.AddOrUpdate(r => r.Title, r77);
            db.SaveChanges();

            Movie r78 = new Movie();
            r78.Title = "Jurassic Park";
            r78.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Adventure"));
            r78.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Science Fiction"));
            r78.Tagline = "An adventure 65 million years in the making.";
            r78.ReleaseDate = Convert.ToDateTime("6/11/1993");
            r78.MPAARating = MPAARating.PG13;
            r78.Runtime = 127;
            r78.Actors = "Sam Neill, Laura Dern, Jeff Goldblum, Richard Attenborough, Bob Peck, Martin Ferrero";
            db.Movies.AddOrUpdate(r => r.Title, r78);
            db.SaveChanges();

            Movie r79 = new Movie();
            r79.Title = "Hocus Pocus";
            r79.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Comedy"));
            r79.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Family"));
            r79.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Fantasy"));
            r79.Tagline = "It's just a bunch of Hocus Pocus.";
            r79.ReleaseDate = Convert.ToDateTime("7/16/1993");
            r79.MPAARating = MPAARating.PG;
            r79.Runtime = 96;
            r79.Actors = "Bette Midler, Sarah Jessica Parker, Kathy Najimy, Omri Katz, Thora Birch, Vinessa Shaw";
            db.Movies.AddOrUpdate(r => r.Title, r79);
            db.SaveChanges();

            Movie r80 = new Movie();
            r80.Title = "Dazed and Confused";
            r80.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Comedy"));
            r80.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Drama"));
            r80.Tagline = "See it with a bud.";
            r80.ReleaseDate = Convert.ToDateTime("9/24/1993");
            r80.MPAARating = MPAARating.R;
            r80.Runtime = 102;
            r80.Actors = "Jason London, Rory Cochrane, Wiley Wiggins, Sasha Jenson, Michelle Burke, Adam Goldberg";
            db.Movies.AddOrUpdate(r => r.Title, r80);
            db.SaveChanges();

            Movie r81 = new Movie();
            r81.Title = "Four Weddings and a Funeral";
            r81.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Comedy"));
            r81.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Drama"));
            r81.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Romance"));
            r81.Tagline = "Five good reasons to stay single.";
            r81.ReleaseDate = Convert.ToDateTime("3/9/1994");
            r81.MPAARating = MPAARating.R;
            r81.Runtime = 117;
            r81.Actors = "Hugh Grant, Andie MacDowell, James Fleet, Simon Callow, John Hannah, Kristin Scott Thomas";
            db.Movies.AddOrUpdate(r => r.Title, r81);
            db.SaveChanges();

            Movie r82 = new Movie();
            r82.Title = "The Lion King";
            r82.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Family"));
            r82.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Animation"));
            r82.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Drama"));
            r82.Tagline = "Life's greatest adventure is finding your place in the Circle of Life.";
            r82.ReleaseDate = Convert.ToDateTime("6/23/1994");
            r82.MPAARating = MPAARating.G;
            r82.Runtime = 89;
            r82.Actors = "Jonathan Taylor Thomas, Matthew Broderick, James Earl Jones, Jeremy Irons, Moira Kelly, Niketa Calame";
            db.Movies.AddOrUpdate(r => r.Title, r82);
            db.SaveChanges();

            Movie r83 = new Movie();
            r83.Title = "Forrest Gump";
            r83.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Comedy"));
            r83.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Drama"));
            r83.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Romance"));
            r83.Tagline = "The world will never be the same, once you've seen it through the eyes of Forrest Gump.";
            r83.ReleaseDate = Convert.ToDateTime("7/6/1994");
            r83.MPAARating = MPAARating.PG13;
            r83.Runtime = 142;
            r83.Actors = "Tom Hanks, Robin Wright, Gary Sinise, Mykelti Williamson, Sally Field, Michael Conner Humphreys";
            db.Movies.AddOrUpdate(r => r.Title, r83);
            db.SaveChanges();

            Movie r84 = new Movie();
            r84.Title = "The Shawshank Redemption";
            r84.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Drama"));
            r84.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Crime"));
            r84.Tagline = "Fear can hold you prisoner. Hope can set you free.";
            r84.ReleaseDate = Convert.ToDateTime("9/23/1994");
            r84.MPAARating = MPAARating.R;
            r84.Runtime = 142;
            r84.Actors = "Tim Robbins, Morgan Freeman, Bob Gunton, Clancy Brown, Mark Rolston, James Whitmore";
            db.Movies.AddOrUpdate(r => r.Title, r84);
            db.SaveChanges();

            Movie r85 = new Movie();
            r85.Title = "Pulp Fiction";
            r85.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Thriller"));
            r85.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Crime"));
            r85.Tagline = "Just because you are a character doesn't mean you have character.";
            r85.ReleaseDate = Convert.ToDateTime("10/8/1994");
            r85.MPAARating = MPAARating.R;
            r85.Runtime = 154;
            r85.Actors = "John Travolta, Samuel L. Jackson, Uma Thurman, Bruce Willis, Ving Rhames, Harvey Keitel";
            db.Movies.AddOrUpdate(r => r.Title, r85);
            db.SaveChanges();

            Movie r86 = new Movie();
            r86.Title = "The Usual Suspects";
            r86.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Drama"));
            r86.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Crime"));
            r86.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Thriller"));
            r86.Tagline = "Five Criminals. One Line Up. No Coincidence.";
            r86.ReleaseDate = Convert.ToDateTime("7/19/1995");
            r86.MPAARating = MPAARating.R;
            r86.Runtime = 106;
            r86.Actors = "Stephen Baldwin, Gabriel Byrne, Chazz Palminteri, Kevin Pollak, Pete Postlethwaite, Kevin Spacey";
            db.Movies.AddOrUpdate(r => r.Title, r86);
            db.SaveChanges();

            Movie r87 = new Movie();
            r87.Title = "Toy Story";
            r87.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Animation"));
            r87.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Comedy"));
            r87.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Family"));
            r87.Tagline = "Hang on for the comedy that goes to infinity and beyond!";
            r87.ReleaseDate = Convert.ToDateTime("10/30/1995");
            r87.MPAARating = MPAARating.G;
            r87.Runtime = 81;
            r87.Actors = "Tom Hanks, Tim Allen, Don Rickles, Jim Varney, Wallace Shawn, John Ratzenberger";
            db.Movies.AddOrUpdate(r => r.Title, r87);
            db.SaveChanges();

            Movie r88 = new Movie();
            r88.Title = "Sense and Sensibility";
            r88.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Drama"));
            r88.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Romance"));
            r88.Tagline = "Lose your heart and come to your senses.";
            r88.ReleaseDate = Convert.ToDateTime("12/13/1995");
            r88.MPAARating = MPAARating.PG;
            r88.Runtime = 136;
            r88.Actors = "Kate Winslet, Emma Thompson, Hugh Grant, Tom Wilkinson, Alan Rickman, Imogen Stubbs";
            db.Movies.AddOrUpdate(r => r.Title, r88);
            db.SaveChanges();

            Movie r89 = new Movie();
            r89.Title = "Mission: Impossible";
            r89.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Adventure"));
            r89.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Action"));
            r89.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Thriller"));
            r89.Tagline = "Expect the Impossible.";
            r89.ReleaseDate = Convert.ToDateTime("5/22/1996");
            r89.MPAARating = MPAARating.PG13;
            r89.Runtime = 110;
            r89.Actors = "Tom Cruise, Jon Voight, Emmanuelle Beart, Henry Czerny, Jean Reno, Ving Rhames";
            db.Movies.AddOrUpdate(r => r.Title, r89);
            db.SaveChanges();

            Movie r90 = new Movie();
            r90.Title = "Independence Day";
            r90.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Action"));
            r90.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Adventure"));
            r90.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Science Fiction"));
            r90.Tagline = "Earth. Take a good look. It might be your last.";
            r90.ReleaseDate = Convert.ToDateTime("6/25/1996");
            r90.MPAARating = MPAARating.PG13;
            r90.Runtime = 145;
            r90.Actors = "Will Smith, Bill Pullman, Jeff Goldblum, Mary McDonnell, Judd Hirsch, Robert Loggia";
            db.Movies.AddOrUpdate(r => r.Title, r90);
            db.SaveChanges();

            Movie r91 = new Movie();
            r91.Title = "Austin Powers: International Man of Mystery";
            r91.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Science Fiction"));
            r91.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Comedy"));
            r91.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Crime"));
            r91.Tagline = "If he were any cooler, he'd still be frozen, baby!";
            r91.ReleaseDate = Convert.ToDateTime("5/2/1997");
            r91.MPAARating = MPAARating.PG13;
            r91.Runtime = 94;
            r91.Actors = "Mike Myers, Elizabeth Hurley, Michael York, Mimi Rogers, Seth Green, Fabiana Udenio";
            db.Movies.AddOrUpdate(r => r.Title, r91);
            db.SaveChanges();

            Movie r92 = new Movie();
            r92.Title = "Men in Black";
            r92.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Action"));
            r92.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Adventure"));
            r92.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Comedy"));
            r92.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Science Fiction"));
            r92.Tagline = "Protecting the Earth from the scum of the universe.";
            r92.ReleaseDate = Convert.ToDateTime("7/2/1997");
            r92.MPAARating = MPAARating.PG13;
            r92.Runtime = 98;
            r92.Actors = "Tommy Lee Jones, Will Smith, Linda Fiorentino, Vincent D'Onofrio, Rip Torn, Tony Shalhoub";
            db.Movies.AddOrUpdate(r => r.Title, r92);
            db.SaveChanges();

            Movie r93 = new Movie();
            r93.Title = "Titanic";
            r93.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Drama"));
            r93.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Romance"));
            r93.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Thriller"));
            r93.Tagline = "Nothing on Earth could come between them.";
            r93.ReleaseDate = Convert.ToDateTime("11/18/1997");
            r93.MPAARating = MPAARating.PG13;
            r93.Runtime = 194;
            r93.Actors = "Kate Winslet, Leonardo DiCaprio, Frances Fisher, Billy Zane, Kathy Bates, Gloria Stuart";
            db.Movies.AddOrUpdate(r => r.Title, r93);
            db.SaveChanges();

            Movie r94 = new Movie();
            r94.Title = "The Big Lebowski";
            r94.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Comedy"));
            r94.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Crime"));
            r94.Tagline = "Times like these call for a Big Lebowski.";
            r94.ReleaseDate = Convert.ToDateTime("3/6/1998");
            r94.MPAARating = MPAARating.R;
            r94.Runtime = 117;
            r94.Actors = "Jeff Bridges, John Goodman, Julianne Moore, Steve Buscemi, Philip Seymour Hoffman, David Huddleston";
            db.Movies.AddOrUpdate(r => r.Title, r94);
            db.SaveChanges();

            Movie r95 = new Movie();
            r95.Title = "Shakespeare in Love";
            r95.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Romance"));
            r95.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "History"));
            r95.Tagline = "Love is the only inspiration.";
            r95.ReleaseDate = Convert.ToDateTime("12/11/1998");
            r95.MPAARating = MPAARating.R;
            r95.Runtime = 122;
            r95.Actors = "Joseph Fiennes, Gwyneth Paltrow, Geoffrey Rush, Tom Wilkinson, Judi Dench, Imelda Staunton";
            db.Movies.AddOrUpdate(r => r.Title, r95);
            db.SaveChanges();

            Movie r96 = new Movie();
            r96.Title = "You've Got Mail";
            r96.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Comedy"));
            r96.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Romance"));
            r96.Tagline = "Someone you pass on the street may already be the love of your life.";
            r96.ReleaseDate = Convert.ToDateTime("12/17/1998");
            r96.MPAARating = MPAARating.PG;
            r96.Runtime = 119;
            r96.Actors = "Tom Hanks, Meg Ryan, Katie Sagona, Greg Kinnear, Parker Posey, Jean Stapleton";
            db.Movies.AddOrUpdate(r => r.Title, r96);
            db.SaveChanges();

            Movie r97 = new Movie();
            r97.Title = "Office Space";
            r97.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Comedy"));
            r97.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Crime"));
            r97.Tagline = "Work sucks.";
            r97.ReleaseDate = Convert.ToDateTime("2/19/1999");
            r97.MPAARating = MPAARating.R;
            r97.Runtime = 89;
            r97.Actors = "Ron Livingston, Jennifer Aniston, David Herman, Ajay Naidu, Diedrich Bader, Stephen Root";
            db.Movies.AddOrUpdate(r => r.Title, r97);
            db.SaveChanges();

            Movie r98 = new Movie();
            r98.Title = "Notting Hill";
            r98.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Romance"));
            r98.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Comedy"));
            r98.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Drama"));
            r98.Tagline = "Can the most famous film star in the world fall for the man on the street?";
            r98.ReleaseDate = Convert.ToDateTime("5/13/1999");
            r98.MPAARating = MPAARating.PG13;
            r98.Runtime = 124;
            r98.Actors = "Julia Roberts, Hugh Grant, Gina McKee, Tim McInnerny, Rhys Ifans, Emma Chambers";
            db.Movies.AddOrUpdate(r => r.Title, r98);
            db.SaveChanges();

            Movie r99 = new Movie();
            r99.Title = "Toy Story 2";
            r99.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Animation"));
            r99.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Comedy"));
            r99.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Family"));
            r99.Tagline = "The toys are back!";
            r99.ReleaseDate = Convert.ToDateTime("10/30/1999");
            r99.MPAARating = MPAARating.G;
            r99.Runtime = 92;
            r99.Actors = "Tom Hanks, Tim Allen, Joan Cusack, Kelsey Grammer, Don Rickles, Jim Varney";
            db.Movies.AddOrUpdate(r => r.Title, r99);
            db.SaveChanges();

            Movie r100 = new Movie();
            r100.Title = "Gladiator";
            r100.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Action"));
            r100.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Drama"));
            r100.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Adventure"));
            r100.Tagline = "A Hero Will Rise.";
            r100.ReleaseDate = Convert.ToDateTime("5/1/2000");
            r100.MPAARating = MPAARating.R;
            r100.Runtime = 155;
            r100.Actors = "Russell Crowe, Joaquin Phoenix, Connie Nielsen, Oliver Reed, Richard Harris, Derek Jacobi";
            db.Movies.AddOrUpdate(r => r.Title, r100);
            db.SaveChanges();

            Movie r101 = new Movie();
            r101.Title = "Gone in Sixty Seconds";
            r101.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Action"));
            r101.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Crime"));
            r101.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Thriller"));
            r101.Tagline = "Ice Cold, Hot Wired.";
            r101.ReleaseDate = Convert.ToDateTime("6/9/2000");
            r101.MPAARating = MPAARating.PG13;
            r101.Runtime = 118;
            r101.Actors = "Nicolas Cage, Angelina Jolie, Giovanni Ribisi, Delroy Lindo, Will Patton, Christopher Eccleston";
            db.Movies.AddOrUpdate(r => r.Title, r101);
            db.SaveChanges();

            Movie r102 = new Movie();
            r102.Title = "X-Men";
            r102.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Adventure"));
            r102.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Action"));
            r102.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Science Fiction"));
            r102.Tagline = "Evolution Begins";
            r102.ReleaseDate = Convert.ToDateTime("7/13/2000");
            r102.MPAARating = MPAARating.PG13;
            r102.Runtime = 104;
            r102.Actors = "Patrick Stewart, Hugh Jackman, Ian McKellen, Halle Berry, Famke Janssen, James Marsden";
            db.Movies.AddOrUpdate(r => r.Title, r102);
            db.SaveChanges();

            Movie r103 = new Movie();
            r103.Title = "Miss Congeniality";
            r103.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Comedy"));
            r103.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Crime"));
            r103.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Action"));
            r103.Tagline = "Never Mess With An Agent In A Dress.";
            r103.ReleaseDate = Convert.ToDateTime("12/14/2000");
            r103.MPAARating = MPAARating.PG13;
            r103.Runtime = 111;
            r103.Actors = "Sandra Bullock, Benjamin Bratt, Michael Caine, Candice Bergen, William Shatner, Ernie Hudson";
            db.Movies.AddOrUpdate(r => r.Title, r103);
            db.SaveChanges();

            Movie r104 = new Movie();
            r104.Title = "Bridget Jones's Diary";
            r104.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Comedy"));
            r104.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Romance"));
            r104.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Drama"));
            r104.Tagline = "Health Warning: Adopting Bridget's lifestyle could seriously damage your health.";
            r104.ReleaseDate = Convert.ToDateTime("4/13/2001");
            r104.MPAARating = MPAARating.R;
            r104.Runtime = 97;
            r104.Actors = "Renee Zellweger, Colin Firth, Hugh Grant, Gemma Jones, Jim Broadbent, James Callis";
            db.Movies.AddOrUpdate(r => r.Title, r104);
            db.SaveChanges();

            Movie r105 = new Movie();
            r105.Title = "Legally Blonde";
            r105.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Comedy"));
            r105.Tagline = "Don't judge a book by its hair color!";
            r105.ReleaseDate = Convert.ToDateTime("7/13/2001");
            r105.MPAARating = MPAARating.PG13;
            r105.Runtime = 96;
            r105.Actors = "Reese Witherspoon, Luke Wilson, Selma Blair, Matthew Davis, Victor Garber, Jennifer Coolidge";
            db.Movies.AddOrUpdate(r => r.Title, r105);
            db.SaveChanges();

            Movie r106 = new Movie();
            r106.Title = "Monsters, Inc.";
            r106.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Animation"));
            r106.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Comedy"));
            r106.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Family"));
            r106.Tagline = "We Scare Because We Care.";
            r106.ReleaseDate = Convert.ToDateTime("11/1/2001");
            r106.MPAARating = MPAARating.G;
            r106.Runtime = 92;
            r106.Actors = "John Goodman, Billy Crystal, Mary Gibbs, Steve Buscemi, James Coburn, Jennifer Tilly";
            db.Movies.AddOrUpdate(r => r.Title, r106);
            db.SaveChanges();

            Movie r107 = new Movie();
            r107.Title = "Harry Potter and the Philosopher's Stone";
            r107.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Adventure"));
            r107.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Fantasy"));
            r107.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Family"));
            r107.Tagline = "Let the Magic Begin.";
            r107.ReleaseDate = Convert.ToDateTime("11/16/2001");
            r107.MPAARating = MPAARating.PG;
            r107.Runtime = 152;
            r107.Actors = "Daniel Radcliffe, Rupert Grint, Emma Watson, Richard Harris, Tom Felton, Robbie Coltrane";
            db.Movies.AddOrUpdate(r => r.Title, r107);
            db.SaveChanges();

            Movie r108 = new Movie();
            r108.Title = "Ocean's Eleven";
            r108.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Thriller"));
            r108.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Crime"));
            r108.Tagline = "Are you in or out?";
            r108.ReleaseDate = Convert.ToDateTime("12/7/2001");
            r108.MPAARating = MPAARating.PG13;
            r108.Runtime = 116;
            r108.Actors = "George Clooney, Brad Pitt, Matt Damon, Andy Garcia, Julia Roberts, Casey Affleck";
            db.Movies.AddOrUpdate(r => r.Title, r108);
            db.SaveChanges();

            Movie r109 = new Movie();
            r109.Title = "Harry Potter and the Chamber of Secrets";
            r109.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Adventure"));
            r109.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Fantasy"));
            r109.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Family"));
            r109.Tagline = "Hogwarts is back in session.";
            r109.ReleaseDate = Convert.ToDateTime("11/13/2002");
            r109.MPAARating = MPAARating.PG;
            r109.Runtime = 161;
            r109.Actors = "Daniel Radcliffe, Rupert Grint, Emma Watson, Richard Harris, Alan Rickman, Tom Felton";
            db.Movies.AddOrUpdate(r => r.Title, r109);
            db.SaveChanges();

            Movie r110 = new Movie();
            r110.Title = "Finding Nemo";
            r110.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Animation"));
            r110.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Family"));
            r110.Tagline = "There are 3.7 trillion fish in the ocean, they're looking for one.";
            r110.ReleaseDate = Convert.ToDateTime("5/30/2003");
            r110.MPAARating = MPAARating.G;
            r110.Runtime = 100;
            r110.Actors = "Albert Brooks, Ellen DeGeneres, Alexander Gould, Willem Dafoe, Brad Garrett, Allison Janney";
            db.Movies.AddOrUpdate(r => r.Title, r110);
            db.SaveChanges();

            Movie r111 = new Movie();
            r111.Title = "Love Actually";
            r111.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Comedy"));
            r111.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Romance"));
            r111.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Drama"));
            r111.Tagline = "The ultimate romantic comedy.";
            r111.ReleaseDate = Convert.ToDateTime("9/7/2003");
            r111.MPAARating = MPAARating.R;
            r111.Runtime = 135;
            r111.Actors = "Keira Knightley, Heike Makatsch, Emma Thompson, Laura Linney, Hugh Grant, January Jones";
            db.Movies.AddOrUpdate(r => r.Title, r111);
            db.SaveChanges();

            Movie r112 = new Movie();
            r112.Title = "Elf";
            r112.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Comedy"));
            r112.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Family"));
            r112.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Fantasy"));
            r112.Tagline = "This holiday, discover your inner elf.";
            r112.ReleaseDate = Convert.ToDateTime("10/9/2003");
            r112.MPAARating = MPAARating.PG;
            r112.Runtime = 97;
            r112.Actors = "Will Ferrell, James Caan, Zooey Deschanel, Mary Steenburgen, Daniel Tay, Ed Asner";
            db.Movies.AddOrUpdate(r => r.Title, r112);
            db.SaveChanges();

            Movie r113 = new Movie();
            r113.Title = "Mean Girls";
            r113.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Comedy"));
            r113.Tagline = "Welcome to girl world.";
            r113.ReleaseDate = Convert.ToDateTime("4/30/2004");
            r113.MPAARating = MPAARating.PG13;
            r113.Runtime = 97;
            r113.Actors = "Lindsay Lohan, Rachel McAdams, Tim Meadows, Ana Gasteyer, Amy Poehler, Tina Fey";
            db.Movies.AddOrUpdate(r => r.Title, r113);
            db.SaveChanges();

            Movie r114 = new Movie();
            r114.Title = "Harry Potter and the Prisoner of Azkaban";
            r114.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Adventure"));
            r114.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Fantasy"));
            r114.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Family"));
            r114.Tagline = "Something wicked this way comes.";
            r114.ReleaseDate = Convert.ToDateTime("5/31/2004");
            r114.MPAARating = MPAARating.PG13;
            r114.Runtime = 141;
            r114.Actors = "Daniel Radcliffe, Rupert Grint, Emma Watson, Gary Oldman, David Thewlis, Alan Rickman";
            db.Movies.AddOrUpdate(r => r.Title, r114);
            db.SaveChanges();

            Movie r115 = new Movie();
            r115.Title = "Harry Potter and the Goblet of Fire";
            r115.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Adventure"));
            r115.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Fantasy"));
            r115.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Family"));
            r115.Tagline = "Dark And Difficult Times Lie Ahead.";
            r115.ReleaseDate = Convert.ToDateTime("11/5/2005");
            r115.MPAARating = MPAARating.PG13;
            r115.Runtime = 157;
            r115.Actors = "Daniel Radcliffe, Rupert Grint, Emma Watson, Ralph Fiennes, Michael Gambon, Alan Rickman";
            db.Movies.AddOrUpdate(r => r.Title, r115);
            db.SaveChanges();

            Movie r116 = new Movie();
            r116.Title = "Cars";
            r116.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Animation"));
            r116.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Adventure"));
            r116.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Comedy"));
            r116.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Family"));
            r116.Tagline = "Ahhh... it's got that new movie smell.";
            r116.ReleaseDate = Convert.ToDateTime("6/8/2006");
            r116.MPAARating = MPAARating.G;
            r116.Runtime = 117;
            r116.Actors = "Owen Wilson, Paul Newman, Bonnie Hunt, Larry the Cable Guy, Tony Shalhoub, Cheech Marin";
            db.Movies.AddOrUpdate(r => r.Title, r116);
            db.SaveChanges();

            Movie r117 = new Movie();
            r117.Title = "The Departed";
            r117.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Drama"));
            r117.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Thriller"));
            r117.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Crime"));
            r117.Tagline = "Lies. Betrayal. Sacrifice. How far will you take it?";
            r117.ReleaseDate = Convert.ToDateTime("10/5/2006");
            r117.MPAARating = MPAARating.R;
            r117.Runtime = 151;
            r117.Actors = "Jack Nicholson, Matt Damon, Jack Nicholson, Mark Wahlberg, Martin Sheen, Ray Winstone";
            db.Movies.AddOrUpdate(r => r.Title, r117);
            db.SaveChanges();

            Movie r118 = new Movie();
            r118.Title = "Ratatouille";
            r118.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Animation"));
            r118.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Comedy"));
            r118.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Family"));
            r118.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Fantasy"));
            r118.Tagline = "He's dying to become a chef.";
            r118.ReleaseDate = Convert.ToDateTime("6/22/2007");
            r118.MPAARating = MPAARating.G;
            r118.Runtime = 111;
            r118.Actors = "Patton Oswalt, Ian Holm, Lou Romano, Brian Dennehy, Peter Sohn, Peter O'Toole";
            db.Movies.AddOrUpdate(r => r.Title, r118);
            db.SaveChanges();

            Movie r119 = new Movie();
            r119.Title = "Transformers";
            r119.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Adventure"));
            r119.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Science Fiction"));
            r119.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Action"));
            r119.Tagline = "Their war. Our world.";
            r119.ReleaseDate = Convert.ToDateTime("6/27/2007");
            r119.MPAARating = MPAARating.PG13;
            r119.Runtime = 144;
            r119.Actors = "Shia LaBeouf, Josh Duhamel, Megan Fox, Rachael Taylor, Tyrese Gibson, Jon Voight";
            db.Movies.AddOrUpdate(r => r.Title, r119);
            db.SaveChanges();

            Movie r120 = new Movie();
            r120.Title = "Harry Potter and the Order of the Phoenix";
            r120.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Adventure"));
            r120.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Fantasy"));
            r120.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Family"));
            r120.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Mystery"));
            r120.Tagline = "Evil Must Be Confronted.";
            r120.ReleaseDate = Convert.ToDateTime("6/28/2007");
            r120.MPAARating = MPAARating.PG13;
            r120.Runtime = 138;
            r120.Actors = "Daniel Radcliffe, Rupert Grint, Emma Watson, Michael Gambon, Ralph Fiennes, Tom Felton";
            db.Movies.AddOrUpdate(r => r.Title, r120);
            db.SaveChanges();

            Movie r121 = new Movie();
            r121.Title = "The Dark Knight";
            r121.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Drama"));
            r121.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Action"));
            r121.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Crime"));
            r121.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Thriller"));
            r121.Tagline = "Why So Serious?";
            r121.ReleaseDate = Convert.ToDateTime("7/16/2008");
            r121.MPAARating = MPAARating.PG13;
            r121.Runtime = 152;
            r121.Actors = "Christian Bale, Heath Ledger, Aaron Eckhart, Michael Caine, Maggie Gyllenhaal, Gary Oldman";
            db.Movies.AddOrUpdate(r => r.Title, r121);
            db.SaveChanges();

            Movie r122 = new Movie();
            r122.Title = "Star Trek";
            r122.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Science Fiction"));
            r122.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Action"));
            r122.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Adventure"));
            r122.Tagline = "The future begins.";
            r122.ReleaseDate = Convert.ToDateTime("5/6/2009");
            r122.MPAARating = MPAARating.PG13;
            r122.Runtime = 127;
            r122.Actors = "Chris Pine, Zachary Quinto, Leonard Nimoy, Eric Bana, Bruce Greenwood, Karl Urban";
            db.Movies.AddOrUpdate(r => r.Title, r122);
            db.SaveChanges();

            Movie r123 = new Movie();
            r123.Title = "Up";
            r123.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Animation"));
            r123.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Comedy"));
            r123.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Family"));
            r123.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Adventure"));
            r123.Tagline = "Fly Up to Venezuela";
            r123.ReleaseDate = Convert.ToDateTime("5/13/2009");
            r123.MPAARating = MPAARating.PG;
            r123.Runtime = 96;
            r123.Actors = "Ed Asner, Christopher Plummer, Jordan Nagai, Bob Peterson, Delroy Lindo, Jerome Ranft";
            db.Movies.AddOrUpdate(r => r.Title, r123);
            db.SaveChanges();

            Movie r124 = new Movie();
            r124.Title = "Harry Potter and the Half-Blood Prince";
            r124.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Adventure"));
            r124.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Fantasy"));
            r124.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Family"));
            r124.Tagline = "Dark Secrets Revealed";
            r124.ReleaseDate = Convert.ToDateTime("7/7/2009");
            r124.MPAARating = MPAARating.PG;
            r124.Runtime = 153;
            r124.Actors = "Daniel Radcliffe, Rupert Grint, Emma Watson, Tom Felton, Michael Gambon, Jim Broadbent";
            db.Movies.AddOrUpdate(r => r.Title, r124);
            db.SaveChanges();

            Movie r125 = new Movie();
            r125.Title = "The Princess and the Frog";
            r125.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Romance"));
            r125.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Family"));
            r125.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Animation"));
            r125.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Musical"));
            r125.Tagline = "Every Love Story Begins With a Kiss...";
            r125.ReleaseDate = Convert.ToDateTime("12/8/2009");
            r125.MPAARating = MPAARating.G;
            r125.Runtime = 97;
            r125.Actors = "Anika Noni Rose, Bruno Campos, Keith David, Michael-Leon Wooley, Jennifer Cody, Jim Cummings";
            db.Movies.AddOrUpdate(r => r.Title, r125);
            db.SaveChanges();

            Movie r126 = new Movie();
            r126.Title = "Avatar";
            r126.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Action"));
            r126.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Adventure"));
            r126.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Fantasy"));
            r126.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Science Fiction"));
            r126.Tagline = "Enter the World of Pandora.";
            r126.ReleaseDate = Convert.ToDateTime("12/10/2009");
            r126.MPAARating = MPAARating.PG13;
            r126.Runtime = 162;
            r126.Actors = "Sam Worthington, Zoe Saldana, Sigourney Weaver, Stephen Lang, Michelle Rodriguez, Giovanni Ribisi";
            db.Movies.AddOrUpdate(r => r.Title, r126);
            db.SaveChanges();

            Movie r127 = new Movie();
            r127.Title = "Toy Story 3";
            r127.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Animation"));
            r127.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Family"));
            r127.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Comedy"));
            r127.Tagline = "No toy gets left behind.";
            r127.ReleaseDate = Convert.ToDateTime("6/16/2010");
            r127.MPAARating = MPAARating.G;
            r127.Runtime = 103;
            r127.Actors = "Tom Hanks, Tim Allen, Ned Beatty, Joan Cusack, Michael Keaton, Whoopi Goldberg";
            db.Movies.AddOrUpdate(r => r.Title, r127);
            db.SaveChanges();

            Movie r128 = new Movie();
            r128.Title = "The King's Speech";
            r128.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Drama"));
            r128.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "History"));
            r128.Tagline = "Find your voice.";
            r128.ReleaseDate = Convert.ToDateTime("9/6/2010");
            r128.MPAARating = MPAARating.R;
            r128.Runtime = 118;
            r128.Actors = "Colin Firth, Geoffrey Rush, Helena Bonham Carter, Guy Pearce, Timothy Spall, Michael Gambon";
            db.Movies.AddOrUpdate(r => r.Title, r128);
            db.SaveChanges();

            Movie r129 = new Movie();
            r129.Title = "Moneyball";
            r129.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Drama"));
            r129.Tagline = "What are you really worth?";
            r129.ReleaseDate = Convert.ToDateTime("9/22/2011");
            r129.MPAARating = MPAARating.PG13;
            r129.Runtime = 133;
            r129.Actors = "Brad Pitt, Jonah Hill, Philip Seymour Hoffman, Robin Wright, Chris Pratt, Stephen Bishop";
            db.Movies.AddOrUpdate(r => r.Title, r129);
            db.SaveChanges();

            Movie r130 = new Movie();
            r130.Title = "Brave";
            r130.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Animation"));
            r130.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Adventure"));
            r130.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Comedy"));
            r130.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Family"));
            r130.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Action"));
            r130.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Fantasy"));
            r130.Tagline = "Change your fate.";
            r130.ReleaseDate = Convert.ToDateTime("6/21/2012");
            r130.MPAARating = MPAARating.PG;
            r130.Runtime = 93;
            r130.Actors = "Kelly Macdonald, Julie Walters, Billy Connolly, Emma Thompson, Kevin McKidd, Craig Ferguson";
            db.Movies.AddOrUpdate(r => r.Title, r130);
            db.SaveChanges();

            Movie r131 = new Movie();
            r131.Title = "Pitch Perfect";
            r131.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Comedy"));
            r131.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Musical"));
            r131.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Romance"));
            r131.Tagline = "Get pitch slapped.";
            r131.ReleaseDate = Convert.ToDateTime("9/28/2012");
            r131.MPAARating = MPAARating.PG13;
            r131.Runtime = 112;
            r131.Actors = "Anna Kendrick, Skylar Astin, Brittany Snow, Anna Camp, Rebel Wilson, Ben Platt";
            db.Movies.AddOrUpdate(r => r.Title, r131);
            db.SaveChanges();

            Movie r132 = new Movie();
            r132.Title = "The Lego Movie";
            r132.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Adventure"));
            r132.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Animation"));
            r132.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Comedy"));
            r132.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Family"));
            r132.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Fantasy"));
            r132.Tagline = "The story of a nobody who saved everybody.";
            r132.ReleaseDate = Convert.ToDateTime("2/6/2014");
            r132.MPAARating = MPAARating.PG;
            r132.Runtime = 100;
            r132.Actors = "Chris Pratt, Will Ferrell, Elizabeth Banks, Will Arnett, Nick Offerman, Alison Brie";
            db.Movies.AddOrUpdate(r => r.Title, r132);
            db.SaveChanges();

            Movie r133 = new Movie();
            r133.Title = "Guardians of the Galaxy";
            r133.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Action"));
            r133.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Science Fiction"));
            r133.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Adventure"));
            r133.Tagline = "All heroes start somewhere.";
            r133.ReleaseDate = Convert.ToDateTime("7/30/2014");
            r133.MPAARating = MPAARating.PG13;
            r133.Runtime = 121;
            r133.Actors = "Chris Pratt, Zoe Saldana, Dave Bautista, Vin Diesel, Bradley Cooper, Lee Pace";
            db.Movies.AddOrUpdate(r => r.Title, r133);
            db.SaveChanges();

            Movie r134 = new Movie();
            r134.Title = "Bad Moms";
            r134.Genres.Add(db.Genres.FirstOrDefault(x => x.GenreName == "Comedy"));
            r134.Tagline = "Party like a mother.";
            r134.ReleaseDate = Convert.ToDateTime("7/28/2016");
            r134.MPAARating = MPAARating.R;
            r134.Runtime = 100;
            r134.Actors = "Mila Kunis, Kristen Bell, Kathryn Hahn, Christina Applegate, Jada Pinkett Smith, Annie Mumolo";
            db.Movies.AddOrUpdate(r => r.Title, r134);
            db.SaveChanges();






        }
    }
}